routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
/*
Route::get('/user', 'UserController@index');
Route::get('/user-register', 'UserController@create');
Route::post('/user-register', 'UserController@store');
Route::get('/user-edit/{id}', 'UserController@edit');
*/
Route::resource('user', 'UserController');

Route::resource('anggota', 'AnggotaController');

Route::resource('buku', 'BukuController');
Route::get('/format_buku', 'BukuController@format');
Route::post('/import_buku', 'BukuController@import');

Route::resource('transaksi', 'TransaksiController');
Route::get('/laporan/trs', 'LaporanController@transaksi');
Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

Route::get('/laporan/buku', 'LaporanController@buku');
Route::get('/laporan/buku/pdf', 'LaporanController@bukuPdf');
Route::get('/laporan/buku/excel', 'LaporanController@bukuExcel');

app/Buku.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    protected $table = 'buku';
    protected $fillable = ['judul', 'isbn', 'penerbit', 'pengarang', 'tahun_terbit', 'jumlah_buku', 'lokasi', 'deskripsi', 'cover'];

    /**
     * Method One To Many
     */
    public function transaksi()
    {
        return $this->hasMany(Transaksi::class);
    }
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use App\Buku;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use RealRashid\SweetAlert\Facades\Alert;

class BukuController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $datas = Buku::get();
        return view('buku.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        return view('buku.create');
    }

    public function format()
    {
        $data = [['judul' => null, 'isbn' => null, 'pengarang' => null, 'penerbit' => null, 'tahun_terbit' => null, 'jumlah_buku' => null, 'deskripsi' => null, 'lokasi' => 'rak1/rak2/rak3']];
        $fileName = 'format-buku';


        $export = Excel::create($fileName . date('Y-m-d_H-i-s'), function ($excel) use ($data) {
            $excel->sheet('buku', function ($sheet) use ($data) {
                $sheet->fromArray($data);
            });
        });

        return $export->download('xlsx');
    }

    public function import(Request $request)
    {
        $this->validate($request, [
            'importBuku' => 'required'
        ]);

        if ($request->hasFile('importBuku')) {
            $path = $request->file('importBuku')->getRealPath();

            $data = Excel::load($path, function ($reader) {
            })->get();
            $a = collect($data);

            if (!empty($a) && $a->count()) {
                foreach ($a as $key => $value) {
                    $insert[] = [
                        'judul' => $value->judul,
                        'isbn' => $value->isbn,
                        'pengarang' => $value->pengarang,
                        'penerbit' => $value->penerbit,
                        'tahun_terbit' => $value->tahun_terbit,
                        'jumlah_buku' => $value->jumlah_buku,
                        'deskripsi' => $value->deskripsi,
                        'lokasi' => $value->lokasi,
                        'cover' => NULL];

                    Buku::create($insert[$key]);

                }

            };
        }
        alert()->success('Berhasil.', 'Data telah diimport!');
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul' => 'required|string|max:255',
            'isbn' => 'required|string'
        ]);

        if ($request->file('cover')) {
            $file = $request->file('cover');
            $dt = Carbon::now();
            $acak = $file->getClientOriginalExtension();
            $fileName = rand(11111, 99999) . '-' . $dt->format('Y-m-d-H-i-s') . '.' . $acak;
            $request->file('cover')->move("images/buku", $fileName);
            $cover = $fileName;
        } else {
            $cover = NULL;
        }

        Buku::create([
            'judul' => $request->get('judul'),
            'isbn' => $request->get('isbn'),
            'pengarang' => $request->get('pengarang'),
            'penerbit' => $request->get('penerbit'),
            'tahun_terbit' => $request->get('tahun_terbit'),
            'jumlah_buku' => $request->get('jumlah_buku'),
            'deskripsi' => $request->get('deskripsi'),
            'lokasi' => $request->get('lokasi'),
            'cover' => $cover
        ]);

        alert()->success('Berhasil.', 'Data telah ditambahkan!');

        return redirect()->route('buku.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Buku $buku
     * @return \Illuminate\Http\Response
     */
    public function show(Buku $buku)
    {
        if (Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $data = Buku::findOrFail($id);

        return view('buku.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Buku $buku
     * @return \Illuminate\Http\Response
     */
    public function edit(Buku $buku)
    {
        if (Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $data = Buku::findOrFail($buku->id);
        return view('buku.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Buku $buku
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Buku $buku)
    {
        if ($request->file('cover')) {
            $file = $request->file('cover');
            $dt = Carbon::now();
            $acak = $file->getClientOriginalExtension();
            $fileName = rand(11111, 99999) . '-' . $dt->format('Y-m-d-H-i-s') . '.' . $acak;
            $request->file('cover')->move("images/buku", $fileName);
            $cover = $fileName;
        } else {
            $cover = NULL;
        }

        Buku::find($buku->id)->update([
            'judul' => $request->get('judul'),
            'isbn' => $request->get('isbn'),
            'pengarang' => $request->get('pengarang'),
            'penerbit' => $request->get('penerbit'),
            'tahun_terbit' => $request->get('tahun_terbit'),
            'jumlah_buku' => $request->get('jumlah_buku'),
            'deskripsi' => $request->get('deskripsi'),
            'lokasi' => $request->get('lokasi'),
            'cover' => $cover
        ]);

        alert()->success('Berhasil.', 'Data telah diubah!');
        return redirect()->route('buku.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Buku $buku
     * @return \Illuminate\Http\Response
     */
    public function destroy(Buku $buku)
    {
        Buku::find($buku->id)->delete();
        alert()->success('Berhasil.', 'Data telah dihapus!');
        return redirect()->route('buku.index');
    }
}

resources/views/buku/create.blade.php
@section('js')

    <script type="text/javascript">
        $(document).ready(function () {
            $(".users").select2();
        });
    </script>

    <script type="text/javascript">
        function readURL() {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(input).prev().attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(function () {
            $(".uploads").change(readURL)
            $("#f").submit(function () {
                // do ajax submit or just classic form submit
                //  alert("fake subminting")
                return false
            })
        })
    </script>
@stop

@extends('layouts.app')

@section('content')

    <form method="POST" action="{{ route('buku.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Tambah Buku baru</h4>

                                <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                    <label for="judul" class="col-md-4 control-label">Judul</label>
                                    <div class="col-md-6">
                                        <input id="judul" type="text" class="form-control" name="judul"
                                               value="{{ old('judul') }}" required>
                                        @if ($errors->has('judul'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('judul') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('npm') ? ' has-error' : '' }}">
                                    <label for="isbn" class="col-md-4 control-label">ISBN</label>
                                    <div class="col-md-6">
                                        <input id="isbn" type="text" class="form-control" name="isbn"
                                               value="{{ old('isbn') }}" required>
                                        @if ($errors->has('isbn'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('isbn') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('pengarang') ? ' has-error' : '' }}">
                                    <label for="pengarang" class="col-md-4 control-label">Pengarang</label>
                                    <div class="col-md-6">
                                        <input id="pengarang" type="text" class="form-control" name="pengarang"
                                               value="{{ old('pengarang') }}" required>
                                        @if ($errors->has('pengarang'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('pengarang') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('penerbit') ? ' has-error' : '' }}">
                                    <label for="penerbit" class="col-md-4 control-label">Penerbit</label>
                                    <div class="col-md-6">
                                        <input id="penerbit" type="text" class="form-control" name="penerbit"
                                               value="{{ old('penerbit') }}" required>
                                        @if ($errors->has('penerbit'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('penerbit') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('tahun_terbit') ? ' has-error' : '' }}">
                                    <label for="tahun_terbit" class="col-md-4 control-label">Tahun Terbit</label>
                                    <div class="col-md-6">
                                        <input id="tahun_terbit" type="number" maxlength="4" class="form-control"
                                               name="tahun_terbit" value="{{ old('tahun_terbit') }}" required>
                                        @if ($errors->has('tahun_terbit'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('tahun_terbit') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('jumlah_buku') ? ' has-error' : '' }}">
                                    <label for="jumlah_buku" class="col-md-4 control-label">Jumlah Buku</label>
                                    <div class="col-md-6">
                                        <input id="jumlah_buku" type="number" maxlength="4" class="form-control"
                                               name="jumlah_buku" value="{{ old('jumlah_buku') }}" required>
                                        @if ($errors->has('jumlah_buku'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('jumlah_buku') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
                                    <label for="deskripsi" class="col-md-4 control-label">Deskripsi</label>
                                    <div class="col-md-12">
                                        <input id="deskripsi" type="text" class="form-control" name="deskripsi"
                                               value="{{ old('deskripsi') }}">
                                        @if ($errors->has('deskripsi'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('deskripsi') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('lokasi') ? ' has-error' : '' }}">
                                    <label for="lokasi" class="col-md-4 control-label">Lokasi</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="lokasi" required="">
                                            <option value=""></option>
                                            <option value="rak1">Rak 1</option>
                                            <option value="rak2">Rak 2</option>
                                            <option value="rak3">Rak 3</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="email" class="col-md-4 control-label">Cover</label>
                                    <div class="col-md-6">
                                        <img width="200" height="200"/>
                                        <input type="file" class="uploads form-control" style="margin-top: 20px;"
                                               name="cover">
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('buku.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
@endsection

resources/views/buku/edit.blade.php
@section('js')

    <script type="text/javascript">
        $(document).ready(function () {
            $(".users").select2();
        });
    </script>

    <script type="text/javascript">
        function readURL() {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(input).prev().attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(function () {
            $(".uploads").change(readURL)
            $("#f").submit(function () {
                // do ajax submit or just classic form submit
                //  alert("fake subminting")
                return false
            })
        })
    </script>
@stop

@extends('layouts.app')

@section('content')

    <form action="{{ route('buku.update', $data->id) }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('put') }}
        <div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Edit Buku <b>{{$data->judul}}</b></h4>
                                <form class="forms-sample">
                                    <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                        <label for="judul" class="col-md-4 control-label">Judul</label>
                                        <div class="col-md-6">
                                            <input id="judul" type="text" class="form-control" name="judul"
                                                   value="{{ $data->judul }}" required>
                                            @if ($errors->has('judul'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('judul') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('npm') ? ' has-error' : '' }}">
                                        <label for="isbn" class="col-md-4 control-label">ISBN</label>
                                        <div class="col-md-6">
                                            <input id="isbn" type="text" class="form-control" name="isbn"
                                                   value="{{ $data->isbn }}" required>
                                            @if ($errors->has('isbn'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('isbn') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('pengarang') ? ' has-error' : '' }}">
                                        <label for="pengarang" class="col-md-4 control-label">Pengarang</label>
                                        <div class="col-md-6">
                                            <input id="pengarang" type="text" class="form-control" name="pengarang"
                                                   value="{{ $data->pengarang }}" required>
                                            @if ($errors->has('pengarang'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('pengarang') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('penerbit') ? ' has-error' : '' }}">
                                        <label for="penerbit" class="col-md-4 control-label">Penerbit</label>
                                        <div class="col-md-6">
                                            <input id="penerbit" type="text" class="form-control" name="penerbit"
                                                   value="{{ $data->penerbit }}" required>
                                            @if ($errors->has('penerbit'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('penerbit') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('tahun_terbit') ? ' has-error' : '' }}">
                                        <label for="tahun_terbit" class="col-md-4 control-label">Tahun Terbit</label>
                                        <div class="col-md-6">
                                            <input id="tahun_terbit" type="number" maxlength="4" class="form-control"
                                                   name="tahun_terbit" value="{{ $data->tahun_terbit }}" required>
                                            @if ($errors->has('tahun_terbit'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('tahun_terbit') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('jumlah_buku') ? ' has-error' : '' }}">
                                        <label for="jumlah_buku" class="col-md-4 control-label">Jumlah Buku</label>
                                        <div class="col-md-6">
                                            <input id="jumlah_buku" type="number" maxlength="4" class="form-control"
                                                   name="jumlah_buku" value="{{ $data->jumlah_buku }}" required>
                                            @if ($errors->has('jumlah_buku'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('jumlah_buku') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
                                        <label for="deskripsi" class="col-md-4 control-label">Deskripsi</label>
                                        <div class="col-md-12">
                                            <input id="deskripsi" type="text" class="form-control" name="deskripsi"
                                                   value="{{ $data->deskripsi }}">
                                            @if ($errors->has('deskripsi'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('deskripsi') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('lokasi') ? ' has-error' : '' }}">
                                        <label for="lokasi" class="col-md-4 control-label">Lokasi</label>
                                        <div class="col-md-6">
                                            <select class="form-control" name="lokasi" required="">
                                                <option value="rak1" {{$data->lokasi === "rak1" ? "selected" : ""}}>Rak
                                                    1
                                                </option>
                                                <option value="rak2" {{$data->lokasi === "rak2" ? "selected" : ""}}>Rak
                                                    2
                                                </option>
                                                <option value="rak3" {{$data->lokasi === "rak3" ? "selected" : ""}}>Rak
                                                    3
                                                </option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="email" class="col-md-4 control-label">Cover</label>
                                        <div class="col-md-6">
                                            <img width="200" height="200"
                                                 @if($data->cover) src="{{ asset('images/buku/'.$data->cover) }}" @endif />
                                            <input type="file" class="uploads form-control" style="margin-top: 20px;"
                                                   name="cover">
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-primary" id="submit">
                                        Update
                                    </button>
                                    <a href="{{route('buku.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
@endsection