routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
/*
Route::get('/user', 'UserController@index');
Route::get('/user-register', 'UserController@create');
Route::post('/user-register', 'UserController@store');
Route::get('/user-edit/{id}', 'UserController@edit');
*/
Route::resource('user', 'UserController');

Route::resource('anggota', 'AnggotaController');

Route::resource('buku', 'BukuController');
Route::get('/format_buku', 'BukuController@format');
Route::post('/import_buku', 'BukuController@import');

Route::resource('transaksi', 'TransaksiController');
Route::get('/laporan/trs', 'LaporanController@transaksi');
Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

Route::get('/laporan/buku', 'LaporanController@buku');
Route::get('/laporan/buku/pdf', 'LaporanController@bukuPdf');
Route::get('/laporan/buku/excel', 'LaporanController@bukuExcel');

app/Anggota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anggota extends Model
{
    protected $table = 'anggota';
    protected $fillable = ['user_id', 'npm', 'nama', 'tempat_lahir', 'tgl_lahir', 'jk', 'prodi'];


    /**
     * Method One To One
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Method One To Many
     */
    public function transaksi()
    {
        return $this->hasMany(Transaksi::class);
    }
}

app/Http/Controllers/AnggotaController.php
<?php

namespace App\Http\Controllers;

use App\Anggota;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use RealRashid\SweetAlert\Facades\Alert;

class AnggotaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $datas = Anggota::get();
        return view('anggota.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $users = User::WhereNotExists(function ($query) {
            $query->select(DB::raw(1))
                ->from('anggota')
                ->whereRaw('anggota.user_id = users.id');
        })->get();
        return view('anggota.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $count = Anggota::where('npm', $request->input('npm'))->count();

        if ($count > 0) {
            Session::flash('message', 'Already exist!');
            Session::flash('message_type', 'danger');
            return redirect()->to('anggota');
        }

        $this->validate($request, [
            'nama' => 'required|string|max:255',
            'npm' => 'required|string|max:20|unique:anggota'
        ]);

        Anggota::create($request->all());

        alert()->success('Berhasil.', 'Data telah ditambahkan!');
        return redirect()->route('anggota.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Anggota $anggota
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ((Auth::user()->level == 'user') && (Auth::user()->id != $id)) {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $data = Anggota::findOrFail($id);

        return view('anggota.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Anggota $anggota
     * @return \Illuminate\Http\Response
     */
    public function edit(Anggota $anggota)
    {
        if ((Auth::user()->level == 'user') && (Auth::user()->id != $anggota->id)) {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $data = Anggota::findOrFail($anggota->id);
        $users = User::get();
        return view('anggota.edit', compact('data', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Anggota $anggota
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Anggota $anggota)
    {
        Anggota::find($anggota->id)->update($request->all());

        alert()->success('Berhasil.', 'Data telah diubah!');
        return redirect()->to('anggota');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Anggota $anggota
     * @return \Illuminate\Http\Response
     */
    public function destroy(Anggota $anggota)
    {
        Anggota::find($anggota->id)->delete();
        alert()->success('Berhasil.', 'Data telah dihapus!');
        return redirect()->route('anggota.index');
    }
}

resources/views/anggota/create.blade.php
@section('js')

    <script type="text/javascript">
        $(document).ready(function () {
            $(".users").select2();
        });
    </script>
@stop

@extends('layouts.app')

@section('content')

    <form method="POST" action="{{ route('anggota.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Tambah Anggota baru</h4>

                                <div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
                                    <label for="nama" class="col-md-4 control-label">Nama</label>
                                    <div class="col-md-6">
                                        <input id="nama" type="text" class="form-control" name="nama"
                                               value="{{ old('nama') }}" required>
                                        @if ($errors->has('nama'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('nama') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('npm') ? ' has-error' : '' }}">
                                    <label for="npm" class="col-md-4 control-label">NPM</label>
                                    <div class="col-md-6">
                                        <input id="npm" type="number" class="form-control" name="npm"
                                               value="{{ old('npm') }}" maxlength="8" required>
                                        @if ($errors->has('npm'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('npm') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('tempat_lahir') ? ' has-error' : '' }}">
                                    <label for="tempat_lahir" class="col-md-4 control-label">Tempat Lahir</label>
                                    <div class="col-md-6">
                                        <input id="tempat_lahir" type="text" class="form-control" name="tempat_lahir"
                                               value="{{ old('tempat_lahir') }}" required>
                                        @if ($errors->has('tempat_lahir'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('tempat_lahir') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('tgl_lahir') ? ' has-error' : '' }}">
                                    <label for="tgl_lahir" class="col-md-4 control-label">Tanggal Lahir</label>
                                    <div class="col-md-6">
                                        <input id="tgl_lahir" type="date" class="form-control" name="tgl_lahir"
                                               value="{{ old('tgl_lahir') }}" required>
                                        @if ($errors->has('tgl_lahir'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('tgl_lahir') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('level') ? ' has-error' : '' }}">
                                    <label for="level" class="col-md-4 control-label">Jenis Kelamin</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="jk" required="">
                                            <option value=""></option>
                                            <option value="L">Laki - Laki</option>
                                            <option value="P">Perempuan</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('prodi') ? ' has-error' : '' }}">
                                    <label for="prodi" class="col-md-4 control-label">Prodi</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="prodi" required="">
                                            <option value=""></option>
                                            <option value="TI">Teknik Informatika</option>
                                            <option value="SI">Sistem Informasi</option>
                                            <option value="KM">Kesehatan Masyarakat</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }} "
                                     style="margin-bottom: 20px;">
                                    <label for="user_id" class="col-md-4 control-label">User Login</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="user_id" required="">
                                            <option value="">(Cari User)</option>
                                            @foreach($users as $user)
                                                <option value="{{$user->id}}">{{$user->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('anggota.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
@endsection

resources/views/anggota/edit.blade.php
@section('js')

    <script type="text/javascript">
        $(document).ready(function () {
            $(".users").select2();
        });
    </script>
@stop

@extends('layouts.app')

@section('content')

    <form action="{{ route('anggota.update', $data->id) }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('put') }}
        <div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
                <div class="row flex-grow">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Edit Anggota</h4>

                                <div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
                                    <label for="nama" class="col-md-4 control-label">Nama</label>
                                    <div class="col-md-6">
                                        <input id="nama" type="text" class="form-control" name="nama"
                                               value="{{ $data->nama }}" required>
                                        @if ($errors->has('nama'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('nama') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('npm') ? ' has-error' : '' }}">
                                    <label for="npm" class="col-md-4 control-label">NPM</label>
                                    <div class="col-md-6">
                                        <input id="npm" type="number" class="form-control" name="npm"
                                               value="{{ $data->npm }}" maxlength="8" required>
                                        @if ($errors->has('npm'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('npm') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group{{ $errors->has('tempat_lahir') ? ' has-error' : '' }}">
                                    <label for="tempat_lahir" class="col-md-4 control-label">Tempat Lahir</label>
                                    <div class="col-md-6">
                                        <input id="tempat_lahir" type="text" class="form-control" name="tempat_lahir"
                                               value="{{ $data->tempat_lahir }}" required>
                                        @if ($errors->has('tempat_lahir'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('tempat_lahir') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('tgl_lahir') ? ' has-error' : '' }}">
                                    <label for="tgl_lahir" class="col-md-4 control-label">Tanggal Lahir</label>
                                    <div class="col-md-6">
                                        <input id="tgl_lahir" type="date" class="form-control" name="tgl_lahir"
                                               value="{{ $data->tgl_lahir }}" required>
                                        @if ($errors->has('tgl_lahir'))
                                            <span class="help-block">
                                        <strong>{{ $errors->first('tgl_lahir') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('level') ? ' has-error' : '' }}">
                                    <label for="level" class="col-md-4 control-label">Jenis Kelamin</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="jk" required="">
                                            <option value=""></option>
                                            <option value="L" {{$data->jk === "L" ? "selected" : ""}}>Laki - Laki
                                            </option>
                                            <option value="P" {{$data->jk === "P" ? "selected" : ""}}>Perempuan</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('prodi') ? ' has-error' : '' }}">
                                    <label for="prodi" class="col-md-4 control-label">Prodi</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="prodi" required="">
                                            <option value=""></option>
                                            <option value="TI" {{$data->prodi === "TI" ? "selected" : ""}} >Teknik
                                                Informatika
                                            </option>
                                            <option value="SI" {{$data->prodi === "SI" ? "selected" : ""}} >Sistem
                                                Informasi
                                            </option>
                                            <option value="KM" {{$data->prodi === "KM" ? "selected" : ""}} >Kesehatan
                                                Masyarakat
                                            </option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }} "
                                     style="margin-bottom: 20px;">
                                    <label for="user_id" class="col-md-4 control-label">User Login</label>
                                    <div class="col-md-6">
                                        <select class="form-control" name="user_id" required="">
                                            <option value="">(Cari User)</option>
                                            @foreach($users as $user)
                                                <option
                                                    value="{{$user->id}}" {{$data->user_id === $user->id ? "selected" : ""}}>{{$user->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary" id="submit">
                                    Ubah
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    Reset
                                </button>
                                <a href="{{route('anggota.index')}}" class="btn btn-light pull-right">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
@endsection

resources/views/anggota/index.blade.php
@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table').DataTable({
                "iDisplayLength": 50
            });
        });
    </script>
@stop
@extends('layouts.app')

@section('content')
    <div class="row">

        <div class="col-lg-2">
            <a href="{{ route('anggota.create') }}" class="btn btn-primary btn-rounded btn-fw"><i
                    class="fa fa-plus"></i> Tambah Anggota</a>
        </div>
        <div class="col-lg-12">
            @if (Session::has('message'))
                <div class="alert alert-{{ Session::get('message_type') }}" id="waktu2"
                     style="margin-top:10px;">{{ Session::get('message') }}</div>
            @endif
        </div>
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">

                <div class="card-body">
                    <h4 class="card-title">Data Anggota</h4>

                    <div class="table-responsive">
                        <table class="table table-striped" id="table">
                            <thead>
                            <tr>
                                <th>
                                    Nama
                                </th>
                                <th>
                                    NPM
                                </th>
                                <th>
                                    Prodi
                                </th>
                                <th>
                                    Jenis Kelamin
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($datas as $data)
                                <tr>
                                    <td class="py-1">
                                        @if($data->user->gambar)
                                            <img src="{{url('images/user', $data->user->gambar)}}" alt="image"
                                                 style="margin-right: 10px;"/>
                                        @else
                                            <img src="{{url('images/user/default.png')}}" alt="image"
                                                 style="margin-right: 10px;"/>
                                        @endif

                                        {{$data->nama}}
                                    </td>
                                    <td>
                                        <a href="{{route('anggota.show', $data->id)}}">
                                            {{$data->npm}}
                                        </a>
                                    </td>

                                    <td>
                                        @if($data->prodi == 'TI')
                                            Teknik Informatika
                                        @elseif($data->prodi == 'SI')
                                            Sistem Informasi
                                        @else
                                            Kesehatan Masyarakat
                                        @endif
                                    </td>
                                    <td>
                                        {{$data->jk === "L" ? "Laki - Laki" : "Perempuan"}}
                                    </td>
                                    <td>
                                        <div class="btn-group dropdown">
                                            <button type="button" class="btn btn-success dropdown-toggle btn-sm"
                                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Action
                                            </button>
                                            <div class="dropdown-menu" x-placement="bottom-start"
                                                 style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                                                <a class="dropdown-item" href="{{route('anggota.edit', $data->id)}}">
                                                    Edit </a>
                                                <form action="{{ route('anggota.destroy', $data->id) }}"
                                                      class="pull-left" method="post">
                                                    {{ csrf_field() }}
                                                    {{ method_field('delete') }}
                                                    <button class="dropdown-item"
                                                            onclick="return confirm('Anda yakin ingin menghapus data ini?')">
                                                        Delete
                                                    </button>
                                                </form>

                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{--  {!! $datas->links() !!} --}}
                </div>
            </div>
        </div>
    </div>
@endsection